# XCTF - PWN Challenge - forgot

>Tiến hành viết file [exploit.py](exploit.py) và khai thác:

```
l1j9m4 in ~/0_PWNable_/ADworld_XCTF/Challenge/forgot λ python2 exploit.py
[*] '/home/l1j9m4/0_PWNable_/ADworld_XCTF/Challenge/forgot/forgot_'
    Arch:     i386-32-little
    RELRO:    Partial RELRO
    Stack:    No canary found
    NX:       NX enabled
    PIE:      No PIE (0x8048000)
[+] Starting local process '/home/l1j9m4/0_PWNable_/ADworld_XCTF/Challenge/forgot/forgot_': pid 7639
[+] Opening connection to 111.200.241.244 on port 59848: Done
[*] Switching to interactive mode
cyberpeace{bbda0bb3993707d78a65e677f024f1b4}
[*] Got EOF while reading in interactive
$  
```
